In [21]:
### Tuan Nguyen - DSC609 Module 2 - July 13, 2020
### Perform Ridge Regression AND Lasso on the data of your own choosing.
### Compare AND contrast the results of Ridge and Lasso regression.

In [22]:
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import LassoCV
import pandas as pd
import numpy as np
import warnings

%matplotlib inline
warnings.filterwarnings("ignore")

### Framework > Library > Package > Module

In [ ]:
### Load Data and Set Variables

df = pd.read_csv(r'C:\Users\cg\Desktop\Echo\School\DSC607\Week 2\diabetes.csv')
x = df[['BloodPressure','BMI', 'Age']].values
y = df[['Outcome']].values

### For the outcome variable, 0 is No and 1 is Yes

In [30]:
### Linear Regression

import statsmodels.api as sm
import statsmodels.formula.api as smf

linear = smf.ols('Outcome ~ BloodPressure + BMI + Age', data = df).fit()
print(linear.summary())

                            OLS Regression Results                            
Dep. Variable:                Outcome   R-squared:                       0.143
Model:                            OLS   Adj. R-squared:                  0.140
Method:                 Least Squares   F-statistic:                     42.57
Date:                Wed, 15 Jul 2020   Prob (F-statistic):           1.92e-25
Time:                        12:41:31   Log-Likelihood:                -461.31
No. Observations:                 768   AIC:                             930.6
Df Residuals:                     764   BIC:                             949.2
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -0.4396      0.085     -5.161

In [31]:
### Ridge Regression
lambdas = 10**np.linspace(10,-2,100)
ridge = RidgeCV(alphas = lambdas, normalize = True)
ridge.fit(x,y)

RidgeCV(alphas=array([1.00000000e+10, 7.56463328e+09, 5.72236766e+09, 4.32876128e+09,
       3.27454916e+09, 2.47707636e+09, 1.87381742e+09, 1.41747416e+09,
       1.07226722e+09, 8.11130831e+08, 6.13590727e+08, 4.64158883e+08,
       3.51119173e+08, 2.65608778e+08, 2.00923300e+08, 1.51991108e+08,
       1.14975700e+08, 8.69749003e+07, 6.57933225e+07, 4.97702356e+07,
       3.76493581e+07, 2.84803587e+0...
       2.00923300e+00, 1.51991108e+00, 1.14975700e+00, 8.69749003e-01,
       6.57933225e-01, 4.97702356e-01, 3.76493581e-01, 2.84803587e-01,
       2.15443469e-01, 1.62975083e-01, 1.23284674e-01, 9.32603347e-02,
       7.05480231e-02, 5.33669923e-02, 4.03701726e-02, 3.05385551e-02,
       2.31012970e-02, 1.74752840e-02, 1.32194115e-02, 1.00000000e-02]),
        cv=None, fit_intercept=True, gcv_mode=None, normalize=True,
        scoring=None, store_cv_values=False)

In [32]:
### Find the best Tuning Parameter (Lambda, or the Ridge Regression Penalty) of the Ridge Regression with:
ridge.alpha_

0.02310129700083158

In [33]:
### Find the coefficients of the Ridge Regression with:
ridge.coef_

array([[-0.0018405 ,  0.01803721,  0.00972941]])

In [34]:
### Find the Intercept of the Ridge Regression with:
ridge.intercept_

array([-0.42432393])

In [35]:
### Lasso Regression
lambdas = 10**np.linspace(10,-2,100)
lasso = LassoCV(alphas = lambdas, normalize = True)
lasso.fit(x,y)

LassoCV(alphas=array([1.00000000e+10, 7.56463328e+09, 5.72236766e+09, 4.32876128e+09,
       3.27454916e+09, 2.47707636e+09, 1.87381742e+09, 1.41747416e+09,
       1.07226722e+09, 8.11130831e+08, 6.13590727e+08, 4.64158883e+08,
       3.51119173e+08, 2.65608778e+08, 2.00923300e+08, 1.51991108e+08,
       1.14975700e+08, 8.69749003e+07, 6.57933225e+07, 4.97702356e+07,
       3.76493581e+07, 2.84803587e+0...
       2.15443469e-01, 1.62975083e-01, 1.23284674e-01, 9.32603347e-02,
       7.05480231e-02, 5.33669923e-02, 4.03701726e-02, 3.05385551e-02,
       2.31012970e-02, 1.74752840e-02, 1.32194115e-02, 1.00000000e-02]),
        copy_X=True, cv=None, eps=0.001, fit_intercept=True, max_iter=1000,
        n_alphas=100, n_jobs=None, normalize=True, positive=False,
        precompute='auto', random_state=None, selection='cyclic', tol=0.0001,
        verbose=False)

In [36]:
### Find the best Tuning Parameter (Lambda, or the Lasso Regression Penalty) of the Ridge Regression with:
lasso.alpha_

10000000000.0

In [45]:
### Find the coefficients of the Lasso Regression with:
lasso.coef_

array([0., 0., 0.])

In [43]:
### Find the Intercept of the Lasso Regression with:
lasso.intercept_

0.3489583333333333

In [44]:
### Ridge vs. Lasso Regression

### like linear regression, both ridge and lasso regressions are linear models that make predictions using a linear function with input variables.
### Both models are similar in that they both introduce some bias into linear models so there can be a decrease in variance when applying the model to test data.
### The formula for both models start with taking the sum of squared residuals then applying a penalty to the sum of squared residuals.

### For Ridge (L2) Regression, the penalty/alpha/tuning parameter is (Lambda + The Slope Squared). 
### For Lasso (L1) Regression, the penalty/alpha/tuning parameter is (Lambda + The Absolute Value of the Slope)
### For both regressions, the value of lambda is arbitary and determines the severity of the penalty.
### The main difference between ridge and lasso regression is that while ridge regression can only shrink the slope asymptotically close to zero, lasso regression can shrink the slope all the way to zero.

In [ ]:
### Compare and Contrast the results of the Models

### Lambda can be any number from zero to infinity, and as lambda increases, the slope of the line will get smaller and smaller. 
### The Lambda for the ridge regression was 0.02310129700083158 while the Lambda for the lasso regression was a very high 10000000000.0
### With the ridge regression, we see the coefficients come out to -0.0018405 ,  0.01803721, and 0.00972941.
### Meanwhile, we see the coefficients for the lasso regression all came out to zero.
### This may seem strange but since the lambda for lasso regression is extremly high, it makes sense that all the coefficients(and therefore the slope) is at zero.
### In speaking with the professor and rewatching this week's lecture, it became clear both ridge and lasso regressions are best used when the number of features (m) is much greater than the number of inputs (n) in our data.
### Since the number of features (m) was not greater than the number of inputs (n) in our data, then the results can become difficult to interpret.

### Another notable difference between the models is in the intercepts. The y-intercept for the ridge regression starts at -0.42432393 while the y-intercept for lasso regression starts a bit higher at 0.3489583333333333